# Generated by Django 4.2.15 on 2024-08-23 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portaluser',
            old_name='dae_register',
            new_name='date_register',
        ),
    ]
